### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Revalto** [AuroraTeam/Launcher#46]
Использую PNPM

Перенес public.pem из LauncherServer получил такую ошибку:
```
[renderer] config.ts(1,19): error TS2307: Cannot find module './public.pem' or its corresponding type declarations.
[renderer] npm run build:renderer exited with code 2
```

ls -l -a
```
drwxr-xr-x  23 revalto  staff     736 Nov  1 15:27 .
drwxr-xr-x  13 revalto  staff     416 Nov  1 15:22 ..
-rw-r--r--   1 revalto  staff     213 Nov  1 15:16 .editorconfig
-rw-r--r--   1 revalto  staff     683 Nov  1 15:16 .eslintrc.js
drwxr-xr-x  12 revalto  staff     384 Nov  1 15:16 .git
drwxr-xr-x   3 revalto  staff      96 Nov  1 15:16 .github
-rw-r--r--   1 revalto  staff     326 Nov  1 15:16 .gitignore
-rw-r--r--   1 revalto  staff      46 Nov  1 15:16 .prettierrc.json
drwxr-xr-x   4 revalto  staff     128 Nov  1 15:16 .vscode
-rw-r--r--   1 revalto  staff    1072 Nov  1 15:16 LICENSE
-rw-r--r--   1 revalto  staff     425 Nov  1 15:16 README.md
drwxr-xr-x@  5 revalto  staff     160 Nov  1 15:17 build
-rw-r--r--   1 revalto  staff     952 Nov  1 15:16 build.mjs
-rw-r--r--   1 revalto  staff     379 Nov  1 15:23 config.ts
drwxr-xr-x@ 45 revalto  staff    1440 Nov  1 15:17 node_modules
-rw-r--r--@  1 revalto  staff    4636 Nov  1 15:17 package.json
-rw-r--r--@  1 revalto  staff  205329 Nov  1 15:17 pnpm-lock.yaml
-rw-r--r--@  1 revalto  staff     800 Nov  1 15:12 public.pem
drwxr-xr-x   3 revalto  staff      96 Nov  1 15:16 resources
drwxr-xr-x   6 revalto  staff     192 Nov  1 15:16 src
-rw-r--r--   1 revalto  staff     802 Nov  1 15:16 tsconfig.json
-rw-r--r--   1 revalto  staff     206 Nov  1 15:16 tsconfig.node.json
-rw-r--r--   1 revalto  staff     797 Nov  1 15:16 vite.config.ts
```

config.ts:
```
import token from './public.pem';

export const window = {
    width: 900,
    height: 550,
    frame: false,
    resizable: false,
    maximizable: false,
    fullscreenable: false,
    title: 'Aurora Launcher',
};

export const api = {
    ws: 'ws://127.0.0.1:1370/ws',
    web: 'http://127.0.0.1:1370',
    // extraToken: token,
};

export const appPath = '.aurora-launcher';
```

Так же отсутствовал пакет при первом запуске: p-map 
```
[main] Build...
[main] ✘ [ERROR] Could not resolve "p-map"
[main] 
[main]     src/main/game/Updater.ts:16:17:
[main]       16 │ import pMap from 'p-map';
[main]          ╵                  ~~~~~~~
[main] 
[main]   You can mark the path "p-map" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
[main] 
```

**Comment by JoCat** [comment]
Вы используете версию лаунчера (v0.0.4) которая не поддерживает работу с токеном, нужно использовать одинаковые версии лаунчера и лаунчсервера

**Comment by StelStelox** [comment]
При работе с 0.0.5 нужно при использования репозитория Launcher нужно нажать галочку выбрать другие ветки.

**Comment by Revalto** [comment]
> Вы используете версию лаунчера (v0.0.4) которая не поддерживает работу с токеном, нужно использовать одинаковые версии лаунчера и лаунчсервера

Может тогда стоит master ветку обновить до 0.0.5 ?

**Comment by StelStelox** [comment]
0.0.5 версия ещё не вышла в релиз
> > Вы используете версию лаунчера (v0.0.4) которая не поддерживает работу с токеном, нужно использовать одинаковые версии лаунчера и лаунчсервера
> 
> Может тогда стоит master ветку обновить до 0.0.5 ?

**Comment by Revalto** [comment]
> 0.0.5 версия ещё не вышла в релиз
> 
> > > Вы используете версию лаунчера (v0.0.4) которая не поддерживает работу с токеном, нужно использовать одинаковые версии лаунчера и лаунчсервера
> > 
> > 
> > Может тогда стоит master ветку обновить до 0.0.5 ?

Просто тогда не понятно, как тогда Laucnher Server под 0.0.5 в релизе. Просто понять не могу. Я вроде и там свежее с master брал и тут с master, а по итогу вот как выходит

**Comment by kostya-main** [comment]
А не чего что он не в релизе а в Pre-release...

**Comment by JoCat** [comment]
> Просто тогда не понятно, как тогда Laucnher Server под 0.0.5 в релизе. Просто понять не могу. Я вроде и там свежее с master брал и тут с master, а по итогу вот как выходит


в мастер ветке лежат 0.0.4 версии, что в лаунчере что в лаунчсервере. И версия 0.0.5 всё ещё в разработке.

**Comment by StelStelox** [comment]
> > 0.0.5 версия ещё не вышла в релиз
> > > > Вы используете версию лаунчера (v0.0.4) которая не поддерживает работу с токеном, нужно использовать одинаковые версии лаунчера и лаунчсервера
> > > 
> > > 
> > > Может тогда стоит master ветку обновить до 0.0.5 ?
> 
> Просто тогда не понятно, как тогда Laucnher Server под 0.0.5 в релизе. Просто понять не могу. Я вроде и там свежее с master брал и тут с master, а по итогу вот как выходит

Просто измени в директории .github/workflows в файле ветку с master на dev

**Comment by Revalto** [comment]
> > Просто тогда не понятно, как тогда Laucnher Server под 0.0.5 в релизе. Просто понять не могу. Я вроде и там свежее с master брал и тут с master, а по итогу вот как выходит
> 
> в мастер ветке лежат 0.0.4 версии, что в лаунчере что в лаунчсервере. И версия 0.0.5 всё ещё в разработке.

> > > 0.0.5 версия ещё не вышла в релиз
> > > > > Вы используете версию лаунчера (v0.0.4) которая не поддерживает работу с токеном, нужно использовать одинаковые версии лаунчера и лаунчсервера
> > > > 
> > > > 
> > > > Может тогда стоит master ветку обновить до 0.0.5 ?
> > 
> > 
> > Просто тогда не понятно, как тогда Laucnher Server под 0.0.5 в релизе. Просто понять не могу. Я вроде и там свежее с master брал и тут с master, а по итогу вот как выходит
> 
> Просто измени в директории .github/workflows в файле ветку с master на dev

Переключился на dev, все заработало.

Может знаете как решить эту проблему? MacOS Sequoia (M1)

```
11/2/2024, 12:05:26 PM [ERROR] Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/revalto/Library/Application Support/.aurora-launcher/clients/OneBlock/natives/liblwjgl.jnilib: dlopen(/Users/revalto/Library/Application Support/.aurora-launcher/clients/OneBlock/natives/liblwjgl.jnilib, 0x0001): tried: '/Users/revalto/Library/Application Support/.aurora-launcher/clients/OneBlock/natives/liblwjgl.jnilib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/revalto/Library/Application Support/.aurora-launcher/clients/OneBlock/natives/liblwjgl.jnilib' (no such file), '/Users/revalto/Library/Application Support/.aurora-launcher/clients/OneBlock/natives/liblwjgl.jnilib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64'))
11/2/2024, 12:05:26 PM [ERROR] at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1869)
	at java.lang.Runtime.loadLibrary0(Runtime.java:844)
	at java.lang.System.loadLibrary(System.java:1136)
	at org.lwjgl.Sys$1.run(Sys.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
11/2/2024, 12:05:26 PM [ERROR] at org.lwjgl.Sys.loadLibrary(Sys.java:95)
	at org.lwjgl.Sys.<clinit>(Sys.java:112)
	at bao.K(SourceFile:2173)
	at net.minecraft.client.main.Main.main(SourceFile:72)
```

**Comment by kostya-main** [comment]
У нас не у кого нет маков по этому спрашивать без смысла. На Discord сервер заходи можешь поискать рассуждения по этому поводу.

Issue я думаю можно закрывать в принципе.
