### ISSUE TITLE
Баг со сменой директории. 

### ISSUE THREAD

**Issue by StelStelox** [AuroraTeam/Launcher#47]
Если директории лаунчера пуста, то при попытки смены директории js не понимает что переносить и просто выводит ошибку
![image](https://github.com/user-attachments/assets/f5b95d61-e79e-4663-996b-c056c54d80fd)

**Comment by kostya-main** [comment]
https://github.com/AuroraTeam/Launcher/commit/ff5c6e9d16f9d795d167a6ab95102a8b4dcbaacd
После этого комита проблема остаётся?

**Comment by StelStelox** [comment]
Сохраняется
![image](https://github.com/user-attachments/assets/702b0144-44e0-47da-a465-ed1a2cfe990d)

**Comment by kostya-main** [comment]
Можешь точнее описать как ты вызываешь ошибку.

**Comment by StelStelox** [comment]
https://github.com/user-attachments/assets/1d7d4627-5b94-4696-899a-315cb0782c4a

**Comment by kostya-main** [comment]
У обычного пользователя не должно получится так что по умолчанию директория пуста. При запуске все папки создаются.

**Comment by StelStelox** [comment]
Правильно. Но всё таки надо это контрить, так как глупые пользователи существуют

**Comment by StelStelox** [comment]
Как бы это можно не фиксить особо

**Comment by kostya-main** [comment]
Какой глупый пользователь сначала удалит все файлы а потом миграцию запустит? Предлагаю закрыть Issue

**Comment by StelStelox** [comment]
Мне кажеться да надо этот закрыть и сделать новый issuse об выводе корректных ошибок
